auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

limits_config:
  ingestion_rate_strategy: global
  ingestion_rate_mb: 20
  ingestion_burst_size_mb: 50
  max_label_name_length: 1024
  max_label_value_length: 2048
  max_label_names_per_series: 30
  per_stream_rate_limit: 50MB
  per_stream_rate_limit_burst: 100MB

ruler:
  alertmanager_url: http://localhost:9093